
print("auto_convert...")

local fi = io.open("script/interface/log_def.h")
if fi == nil then
	return print("open file ./log_def.h error.")
end

local content = fi:read("*a")
fi:close()
--print(content)

local list = {}
for name in string.gmatch(content, "(%w+)(%s*)=(%s*)(%w+)") do
	--print(name)
	table.insert(list, name)
end

local fo = io.open("script/export/log_def.data", "w+")
fo:write("/* generated by log_def.lua. */\n")
for _, name in ipairs(list) do
	fo:write(string.format("logList[%s] = \"%s\";\n", name, name))
end
fo:flush()
fo:close()





print("end!")
